[wandb]
project_name = "ZSPan"
run_name = "separated_test1"
note = "separate FUG and RSP training with ratio 0.7"
enable_wandb = false

[common]
sample_range = [0, 20]
device = "cuda"
satellite = "wv3"
file_path = "../02-Test-toolbox-for-traditional-and-DL(Matlab)-1/1_TestData/PanCollection/test_wv3_OrigScale_multiExm1.h5"

[sde]
lr_sde = 0.0005
epochs = 250
batch_size = 1

[rnd]
lr_fug = 0.0005
lr_rsp = 0.001
ratio = 0.7
warmup = 20
epochs = 250
batch_size = 8

[test]